import re
from langchain_core.messages import SystemMessage, HumanMessage
from ..state import AgentState
from ...utils.rate_limiter import rate_limited_gemini

# Gemini 심사위원 프롬프트
VALIDATOR_PROMPT = """You are a strict Quality Assurance AI for a Korean user.
Evaluate the 'Junior Model Response' based on the 'User Intent'.

User Intent:
{user_intent}

Junior Model Response:
{final_response}

# Evaluation Criteria (Fail if ANY is violated):
1. **Language**: Must be naturally written in **Korean**. (Reject if it contains Chinese characters or is mostly English).
2. **Relevance**: Must directly address the user's intent.
3. **Completeness**: Must not be empty or cut off.

# Output format:
- If satisfactory: Output "VALID"
- If unsatisfactory: Output "INVALID"
"""

def has_chinese_chars(text: str) -> bool:
    """텍스트에 중국어(CJK 한자)가 포함되어 있는지 정규식으로 검사"""
    return bool(re.search(r'[\u4e00-\u9fff]', text))

@rate_limited_gemini
async def validate_answer(state: AgentState, llm):
    """
    Validates the answer generated by the 8B model using Gemini as a judge.
    """
    state["current_node"] = "validate_answer"
    log_message = "---NODE: Validate Answer (Judge: Gemini)---"
    state["log"] = [log_message]
    print(log_message)

    user_intent = state.get("user_intent", "")
    final_response = state.get("final_answer", "")

    # 1. [Fast Fail] Empty response check
    if not final_response:
        fail_log = ">> Validation Failed: Response is empty."
        state["log"].append(fail_log)
        print(fail_log)
        return {"is_final_answer_satisfactory": False}

    # 2. [Fast Fail] Chinese character check (Regex)
    if has_chinese_chars(final_response):
        fail_log = ">> Validation Failed: Chinese characters detected."
        state["log"].append(fail_log)
        print(fail_log)
        return {
            "is_final_answer_satisfactory": False,
            "tool_results": f"[System Error] Local model generated Chinese text. User intent was: {user_intent}"
        }

    # 3. [Deep Check] Gemini LLM-as-a-Judge
    state["log"].append(">> Sending to Gemini for final validation...")
    print(">> Sending to Gemini for final validation...")
    prompt = VALIDATOR_PROMPT.format(
        user_intent=user_intent,
        final_response=final_response
    )
    
    messages = [
        SystemMessage(content="You are a QA Judge."),
        HumanMessage(content=prompt)
    ]
    
    try:
        judge_result = await llm.ainvoke(messages)
        judge_score = judge_result.content.strip().upper()
        
        judge_log = f">> Gemini Judge Result: {judge_score}"
        state["log"].append(judge_log)
        print(judge_log)

        if "INVALID" in judge_score:
            fail_log = ">> Validation Failed: Gemini rejected the response."
            state["log"].append(fail_log)
            print(fail_log)
            return {
                "is_final_answer_satisfactory": False,
                "tool_results": f"[System Error] The previous answer was rejected by QA. Please provide a better answer for: {user_intent}"
            }
            
    except Exception as e:
        error_log = f">> Validation Error (Gemini unavailable): {e}"
        state["log"].append(error_log)
        print(error_log)
        # Gemini 연결 실패 시 검증 스킵
        return {
            "is_final_answer_satisfactory": True,
            "gemini_unavailable": True
        }

    # All checks passed
    success_log = ">> Validation Passed: Perfect Korean response."
    state["log"].append(success_log)
    print(success_log)
    return {"is_final_answer_satisfactory": True}