from typing import Annotated, Sequence, TypedDict, List, Optional, Dict, Any
from langchain_core.messages import BaseMessage
from sqlmodel.ext.asyncio.session import AsyncSession
import operator

class ToolCall(TypedDict):
    """ A planned tool call. """
    name: str
    args: Dict[str, Any]

class ToolResult(TypedDict):
    """ The result of a tool call. """
    tool_name: str
    output: str

class AgentState(TypedDict):
    """
    The state of the agent in the LangGraph.
    It tracks the various pieces of information passed between the nodes.
    """
    # The history of messages in the conversation
    messages: Annotated[Sequence[BaseMessage], operator.add]
    
    # The user's ID
    user_id: int

    # The user's clarified intent
    user_intent: Optional[str]

    # The rewritten prompt after DB lookup
    rewritten_prompt: Optional[str]
    
    # The plan of tools to be called
    plan: Optional[List[ToolCall]]
    
    # Planned tool queue (ordered)
    tool_queue: Optional[List[ToolCall]]
    
    # The results from the executed tools
    tool_results: Optional[List[ToolResult]]

    # Whether DB search returned a hit
    db_hit: Optional[bool]
    
    # The final answer generated by a model
    final_answer: Optional[str]
    
    # A flag to check if the final answer is satisfactory
    is_final_answer_satisfactory: Optional[bool]

    # The database session
    db_session: Optional[AsyncSession]

    # Real-time log of operations
    log: Annotated[List[str], operator.add]

    # The name of the current node being executed
    current_node: Optional[str]
